# Generated by Django 5.2.1 on 2025-05-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome Completo"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefone")),
                (
                    "curriculum",
                    models.FileField(
                        upload_to="curriculums/", verbose_name="Currículo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
            ],
            options={
                "verbose_name": "Collaborator",
                "verbose_name_plural": "Collaborators",
                "ordering": ["name"],
            },
        ),
    ]
